"""made state name unique

Revision ID: 5afed59b6a96
Revises: 56700f246d8b
Create Date: 2024-08-27 09:05:25.045992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afed59b6a96'
down_revision = '56700f246d8b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_state_name', ['name'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
