"""added state name  in places

Revision ID: 7d59476d6dcc
Revises: f1d6c5a8d551
Create Date: 2024-08-26 19:29:34.306151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d59476d6dcc'
down_revision = 'f1d6c5a8d551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('State_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('State_name')

    # ### end Alembic commands ###
