"""commented location in places

Revision ID: f1d6c5a8d551
Revises: ece8f5337a3c
Create Date: 2024-08-26 19:26:48.171687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d6c5a8d551'
down_revision = 'ece8f5337a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
